version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: superset
    AWS_ACCOUNT_ID: 535710392721

phases:
  build:
    commands:
      #- echo Tagging image docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      #- printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - docker buildx create --name ${IMAGE_REPO_NAME} --use
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com

      - echo Build started on `date`
      #- docker buildx build --platform linux/amd64,linux/arm64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/${IMAGE_REPO_NAME}:latest --push .
      - docker buildx build --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/${IMAGE_REPO_NAME}:latest --push .
      - echo Build completed on `date`
      - echo Pushing the Docker image...
  post_build:
    commands:
      - echo Done
